export const cakeGirlPaintings = [
  {
    id: "1",
    name: "painting1",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "2",
    name: "painting2",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "3",
    name: "painting3",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "4",
    name: "painting4",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "5",
    name: "painting5",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "6",
    name: "painting6",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "7",
    name: "painting7",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
  {
    id: "8",
    name: "painting8",
    image: "https://th.bing.com/th/id/OIG.lVXjWwlHyIo4QdjnC1YE",
    description: "2023 18'x24'",
    price: "3000",
    quantity: "1",
  },
];
